#include "stdafx.h"
#include "../UI/UISceneTabBar.h"

namespace
{
    bool scene_ready = false;
    DWORD crash_code = 0;
    void* crash_address = nullptr;

    const size_t emergency_backup_limit = 3;
    const char* const autosave_directory = "_autosave";

    size_t AutoSaveBackupLimit()
    {
        return EPrefs ? _max(1u, _min(EPrefs->scene_autosave_backup_count, 20u)) : 3u;
    }

    // Only names generated by the editor qualify for automatic deletion.
    bool IsBackupName(const xr_string& name, bool emergency)
    {
        const xr_string prefix = emergency ? "last_session_" : "last_autosave_";
        if (name.compare(0, prefix.size(), prefix) != 0)
            return false;
        size_t pos = prefix.size();
        for (size_t count : { size_t(8), size_t(6) })
        {
            for (size_t i = 0; i < count; ++i, ++pos)
                if (pos >= name.size() || name[pos] < '0' || name[pos] > '9')
                    return false;
            if (pos >= name.size() || name[pos++] != '_')
                return false;
        }
        const size_t pid_start = pos;
        while (pos < name.size() && name[pos] >= '0' && name[pos] <= '9')
            ++pos;
        return pos > pid_start && name.substr(pos) == (emergency ? "_fail" : "");
    }

    void PruneBackups(bool emergency)
    {
        // The .level file and its parts folder are one recovery copy. Include
        // orphan folders left behind by an interrupted emergency serialization.
        // FS_RootOnly skips folders entirely, so enumerate the backup directory directly.
        xr_map<xr_string, ULONGLONG> copies;
        string_path pattern;
        string_path relativePattern;
        xr_sprintf(relativePattern, sizeof(relativePattern), "%s*", emergency ? "" : "_autosave\\");
        FS.update_path(pattern, _maps_, relativePattern);
        WIN32_FIND_DATAA entry;
        HANDLE search = FindFirstFileA(pattern, &entry);
        if (search == INVALID_HANDLE_VALUE)
            return;
        do
        {
            if (entry.dwFileAttributes & FILE_ATTRIBUTE_REPARSE_POINT)
                continue;
            xr_string name = entry.cFileName;
            if (!(entry.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY))
            {
                if (name.size() > 6 && name.substr(name.size() - 6) == ".level")
                    name.resize(name.size() - 6);
                else if (name.size() > 7 && name.substr(name.size() - 7) == ".~level")
                    name.resize(name.size() - 7);
                else
                    continue;
            }
            if (IsBackupName(name, emergency))
            {
                const ULONGLONG modified =
                    (ULONGLONG(entry.ftLastWriteTime.dwHighDateTime) << 32) |
                    entry.ftLastWriteTime.dwLowDateTime;
                auto inserted = copies.emplace(name, modified);
                if (!inserted.second && modified > inserted.first->second)
                    inserted.first->second = modified;
            }
        }
        while (FindNextFileA(search, &entry));
        FindClose(search);
        xr_vector<std::pair<xr_string, ULONGLONG>> sorted;
        sorted.reserve(copies.size());
        for (const auto& copy : copies)
            sorted.emplace_back(copy.first, copy.second);
        std::sort(sorted.begin(), sorted.end(), [](const std::pair<xr_string, ULONGLONG>& a,
            const std::pair<xr_string, ULONGLONG>& b)
        {
            return a.second != b.second ? a.second > b.second : a.first > b.first;
        });
        const size_t backupLimit = emergency ? emergency_backup_limit : AutoSaveBackupLimit();
        for (size_t i = backupLimit; i < sorted.size(); ++i)
        {
            string_path path;
            xr_string relativeName = emergency ? sorted[i].first + "\\" : xr_string(autosave_directory) + "\\" + sorted[i].first + "\\";
            FS.update_path(path, _maps_, relativeName.c_str());
            FS.dir_delete(path, TRUE);
            relativeName = emergency ? sorted[i].first + ".level" : xr_string(autosave_directory) + "\\" + sorted[i].first + ".level";
            FS.update_path(path, _maps_, relativeName.c_str());
            FS.file_delete(path);
            relativeName = emergency ? sorted[i].first + ".~level" : xr_string(autosave_directory) + "\\" + sorted[i].first + ".~level";
            FS.update_path(path, _maps_, relativeName.c_str());
            FS.file_delete(path);
        }
    }

    bool MakeBackupPath(string_path& path, bool emergency)
    {
        xr_string relativeDirectory;
        if (!emergency)
        {
            relativeDirectory = xr_string(autosave_directory) + "\\";
            string_path directory;
            FS.update_path(directory, _maps_, relativeDirectory.c_str());
            if (!CreateDirectoryA(directory, nullptr) && GetLastError() != ERROR_ALREADY_EXISTS)
                return false;
        }
        SYSTEMTIME now;
        GetLocalTime(&now);
        string_path name;
        xr_sprintf(name, sizeof(name), "%s%04u%02u%02u_%02u%02u%02u_%lu%s.level",
            emergency ? "last_session_" : "last_autosave_",
            now.wYear, now.wMonth, now.wDay, now.wHour, now.wMinute, now.wSecond,
            GetCurrentProcessId(), emergency ? "_fail" : "");
        relativeDirectory += name;
        FS.update_path(path, _maps_, relativeDirectory.c_str());
        return true;
    }

    int CrashFilter(EXCEPTION_POINTERS* info)
    {
        const DWORD code = info->ExceptionRecord->ExceptionCode;
        // Do not serialize with an exhausted stack or corrupt heap.
        if (IsDebuggerPresent() || code == EXCEPTION_STACK_OVERFLOW ||
            code == 0xC0000374 || code == 0xC0000409)
            return EXCEPTION_CONTINUE_SEARCH;
        crash_code = code;
        crash_address = info->ExceptionRecord->ExceptionAddress;
        return EXCEPTION_EXECUTE_HANDLER;
    }

    bool TryEmergencySave(string_path& path)
    {
        path[0] = '\0';
        __try
        {
            if (!scene_ready || !Scene || Scene->locked() || !Scene->IsUnsaved())
                return false;
            if (!MakeBackupPath(path, true))
                return false;
            Msg("! [CRASH] code=0x%08lX address=%p; attempting backup: %s",
                crash_code, crash_address, path);
            Scene->SaveBackup(path);
            PruneBackups(true);
            FlushLog();
            return true;
        }
        __except (EXCEPTION_EXECUTE_HANDLER)
        {
            return false;
        }
    }

    int RunEditor()
    {
        if (!IsDebuggerPresent())
            Debug._initialize(false);
        Core.InitCore("level", ELogCallback);
        PruneBackups(false);
        PruneBackups(true);
        XrSE_Factory::initialize();
        LTools = xr_new<CLevelTool>();
        Tools = LTools;
        LUI = xr_new<CLevelMain>();
        UI = LUI;
        UI->RegisterCommands();
        Scene = xr_new<EScene>();
        UIMainForm* main_form = xr_new<UIMainForm>();
        ::MainForm = main_form;
        UI->Push(main_form, false);
        if (OpenLauncherDocument())
            UISceneTabBar::OnSceneLoaded(LTools->m_LastFileName.c_str(), nullptr);
        scene_ready = true;

        DWORD last_autosave_time = GetTickCount();
        while (main_form->Frame())
        {
            const DWORD current_time = GetTickCount();
            const DWORD autosave_interval = EPrefs ?
                _max(1u, _min(EPrefs->scene_autosave_interval, 240u)) * 60000u : 600000u;
            if (EPrefs && EPrefs->scene_autosave_enabled && current_time - last_autosave_time >= autosave_interval)
            {
                last_autosave_time = current_time;
                if (Scene && !Scene->locked() && Scene->IsUnsaved())
                {
                    string_path path;
                    if (MakeBackupPath(path, false))
                    {
                        Msg("[Autosave] Saving backup to %s", path);
                        Scene->SaveBackup(path);
                        PruneBackups(false);
                    }
                    else
                        Msg("! [Autosave] Could not create the autosave directory.");
                }
            }
        }
        scene_ready = false;
        xr_delete(main_form);
        XrSE_Factory::destroy();
        Core.DestroyCore();
        return 0;
    }
}

extern "C" int __cdecl SDKEditorMain()
{
    __try
    {
        return RunEditor();
    }
    __except (CrashFilter(GetExceptionInformation()))
    {
        string_path path;
        const bool saved = TryEmergencySave(path);
        char message[2048];
        sprintf_s(message, sizeof(message),
            "Unrecoverable editor error (0x%08lX at %p).\n\n%s\n%s\n\n"
            "The editor will close. Use the last autosave if this recovery copy is incomplete.",
            crash_code, crash_address,
            saved ? "Emergency serialization completed. Check the recovery copy:" :
                "Emergency serialization failed or was unavailable. The copy may be incomplete:",
            path[0] ? path : "No recovery file was created.");
        Msg("! [CRASH] %s", message);
        FlushLog();
        // Missing assets may be tolerated in SDK debug mode, but a fatal crash must be visible.
        MessageBoxA(NULL, message, "SDK recovery", MB_OK | MB_ICONERROR | MB_TASKMODAL);
        // Do not run destructors or another frame against potentially corrupt state.
        ExitProcess(1);
    }
    return 1;
}
