# File-copy and LuaJIT cache checks with a fake batch script. Never invokes MSBuild or a compiler.
$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $PSScriptRoot 'BuildSupport.psm1') -Force
$fixture = Join-Path ([IO.Path]::GetTempPath()) ('sdk-incremental-' + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path $fixture | Out-Null
function Assert($condition, $message) { if (!$condition) { throw $message } }
try {
    $source = Join-Path $fixture 'source.dll'
    $destination = Join-Path $fixture 'installed\source.dll'
    [IO.File]::WriteAllText($source, 'first')
    Assert (Copy-SdkFile $source $destination) 'Missing file was not copied.'
    $time = (Get-Item -LiteralPath $destination).LastWriteTimeUtc
    Assert (!(Copy-SdkFile $source $destination)) 'Unchanged file was recopied.'
    (Get-Item -LiteralPath $source).LastWriteTimeUtc = $time.AddMinutes(1)
    Assert (!(Copy-SdkFile $source $destination)) 'Identical regenerated bytes were recopied.'
    Assert ((Get-Item -LiteralPath $destination).LastWriteTimeUtc -eq $time) 'Destination timestamp changed.'
    [IO.File]::WriteAllText($source, 'other')
    (Get-Item -LiteralPath $source).LastWriteTimeUtc = $time.AddMinutes(2)
    Assert (Copy-SdkFile $source $destination) 'Changed file was not copied.'
    Assert ([IO.File]::ReadAllText($destination) -eq 'other') 'Destination contains stale bytes.'
    Assert (!(Copy-SdkFile $source $source)) 'Self-copy was not skipped.'

    $luaSource = Join-Path $fixture 'External\LuaJIT\src'
    $support = Join-Path $fixture 'SDKRuntime'
    $binary = Join-Path $fixture 'External\LuaJIT\bin\x64'
    foreach ($folder in @($luaSource,$support,$binary)) { New-Item -ItemType Directory -Path $folder -Force | Out-Null }
    Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'BuildSupport.psm1') -Destination $support
    Copy-Item -LiteralPath (Join-Path $PSScriptRoot '..\External\LuaJIT\src\Build-LuaJIT.ps1') -Destination $luaSource
    foreach ($name in @('LuaJIT.dll','LuaJIT.lib','LuaJIT.exp','LuaJIT.pdb')) {
        [IO.File]::WriteAllText((Join-Path $binary $name), "fixture $name")
    }
    $luaScript = Join-Path $luaSource 'Build-LuaJIT.ps1'
    & $luaScript -SolutionRoot $fixture -Platform x64 -Configuration Release -SyncOnly
    $deployed = Join-Path $fixture 'BuildedSDK\x64_Release\LuaJIT.dll'
    $library = Join-Path $fixture 'output\libraries_x64_Release\LuaJIT.lib'
    Assert (Test-Path -LiteralPath $deployed) 'Lua DLL missing after sync.'
    Assert (Test-Path -LiteralPath $library) 'Lua import library missing after sync.'
    $libraryTime = (Get-Item -LiteralPath $library).LastWriteTimeUtc
    Remove-Item -LiteralPath $deployed
    & $luaScript -SolutionRoot $fixture -Platform x64 -Configuration Release -SyncOnly
    Assert (Test-Path -LiteralPath $deployed) 'Missing deployed DLL was not restored.'
    Assert ((Get-Item -LiteralPath $library).LastWriteTimeUtc -eq $libraryTime) 'Import library was unnecessarily touched.'
    # Simulate a successful DLL relink that leaves the unchanged import library's date intact.
    New-Item -ItemType Directory -Path (Join-Path $fixture 'External\LuaJIT\dynasm') -Force | Out-Null
    $importFile = Join-Path $binary 'LuaJIT.lib'
    $oldImportTime = [DateTime]::UtcNow.AddDays(-2)
    (Get-Item -LiteralPath $importFile).LastWriteTimeUtc = $oldImportTime
    [IO.File]::WriteAllText((Join-Path $luaSource 'fixture-dll.txt'), 'relinked fixture DLL')
    [IO.File]::WriteAllText((Join-Path $luaSource 'msvcbuild.bat'), @'
@echo off
copy /Y fixture-dll.txt ..\bin\x64\LuaJIT.dll >nul
if errorlevel 1 exit /b 1
echo invoked>>..\bin\x64\fixture-builds.txt
exit /b 0
'@)
    & $luaScript -SolutionRoot $fixture -Platform x64 -Configuration Release
    Assert ((Get-Item -LiteralPath $importFile).LastWriteTimeUtc -eq $oldImportTime) 'Unchanged import library was touched.'
    Assert (Test-Path -LiteralPath (Join-Path $binary 'sdk-inputs.txt')) 'Successful relink did not save the cache.'
    & $luaScript -SolutionRoot $fixture -Platform x64 -Configuration Release
    Assert (@(Get-Content -LiteralPath (Join-Path $binary 'fixture-builds.txt')).Count -eq 1) 'Cached inputs invoked the batch script again.'
    Remove-Item -LiteralPath $importFile
    $missingImportRejected = $false
    try { & $luaScript -SolutionRoot $fixture -Platform x64 -Configuration Release }
    catch { $missingImportRejected = $true }
    Assert $missingImportRejected 'Missing import library was accepted after a simulated build.'
    Write-Host 'PASS: incremental copy, stable timestamps, LuaJIT sync/cache, unchanged and missing import libraries; no compilation.'
} finally {
    $resolved = [IO.Path]::GetFullPath($fixture)
    $tempRoot = [IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd('\') + '\'
    if (!$resolved.StartsWith($tempRoot, [StringComparison]::OrdinalIgnoreCase) -or
        (Split-Path -Leaf $resolved) -notmatch '^sdk-incremental-[a-f0-9]{32}$') {
        throw 'Refusing to remove a test directory outside the temporary workspace.'
    }
    Remove-Item -LiteralPath $resolved -Recurse -Force
}
