#pragma once
#define IDR_LAUNCHER_LOGO 101
#define IDR_LAUNCHER_ACTOR 102
#define IDR_LAUNCHER_LEVEL 103
#define IDR_LAUNCHER_PARTICLE 104
#define IDR_LAUNCHER_SHADER 105
#define IDR_LAUNCHER_CLOSE 106
#define IDR_LAUNCHER_MINIMIZE 107
#define IDR_LAUNCHER_FONT 108
#define IDR_LAUNCHER_FRAME 109
